export const UI = {
    skip: "Skip to content",
    contents: "Contents",
    search: "Search articles",
    searchPlaceholder: "Search articles...",
    close: "Close",
    closeSearch: "Close search",
    open: "Open",
    navigate: "Navigate",
    backTop: "Back to top",
    imageViewer: "Image viewer",
    original: "Open original",
    loadingImage: "Loading image…",
    imageFailed: "Image could not load. Try opening the original.",
    imagePreviewFailed: "Showing the preview. The larger image could not load.",
    copyCode: "Copy code",
    copied: "Copied",
    copyFailed: "Could not copy. Select the text to copy it manually.",
    wrap: "Wrap lines",
    newTab: " (opens in a new tab)",
    searching: "Searching the archive",
    searchingHelp: "Loading matching sections and excerpts.",
    unavailable: "Search is temporarily unavailable",
    unavailableHelp: "Please try again, or browse the archive.",
    retry: "Retry",
    archive: "View archive",
    reload: "Reload page",
    outdated: "The site has been updated",
    outdatedHelp:
        "Reload this page to search the latest articles. Your current reading position is unchanged.",
    empty: "No articles matched that search",
    emptyHelp: "Try another keyword, title, or shorter phrase.",
    idle: "Type a keyword to start searching",
    idleHelp: "Search posts and jump to matching sections.",
    more: "Show more results",
    partial: "Some results could not load; try searching again.",
    untitled: "Untitled article",
    table: "Scrollable table",
};
